require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

target 'App' do
  # Capacitor dependencies are linked via SPM
  # Add your pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
